networks:
  app_network:
    driver: bridge

volumes:
  postgres-data:

services:
  db:
    image: mirror.gcr.io/library/postgres:16-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: core
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d core']
      interval: 5s
      timeout: 5s
      retries: 5

  db-adminer:
    image: dockette/adminer:full
    container_name: db_adminer
    restart: unless-stopped
    ports:
      - '127.0.0.1:5051:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
      target: production
    container_name: backend
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"
